/**
 * Copyright (c) MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.md file.
 */

package org.mule.module.mongo.automation.testcases;

import static org.junit.Assert.assertTrue;

import java.util.List;

import org.junit.After;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.mule.module.mongo.api.IndexOrder;
import org.mule.module.mongo.api.automation.MongoHelper;
import org.mule.module.mongo.automation.AbstractMongoTest;
import org.mule.module.mongo.automation.RegressionTests;
import org.mule.module.mongo.automation.SmokeTests;

import com.mongodb.DBObject;

public class ListIndexesTestCases extends AbstractMongoTest {

    private String indexName;

    @Override
    public void setUp() {
        getConnector().createCollection("Arenas", false, 5, 5);
        getConnector().createIndex("Arenas", "myField", IndexOrder.ASC);
        indexName = "myField" + "_" + IndexOrder.ASC.getValue();
    }

    @Category({ SmokeTests.class, RegressionTests.class })
    @Test
    public void testListIndices() {
        List<DBObject> payload = (List<DBObject>) getConnector().listIndices("Arenas");

        assertTrue(payload != null);
        assertTrue(MongoHelper.indexExistsInList(payload, "_id_")); // Automatically generated by MongoDB
        assertTrue(MongoHelper.indexExistsInList(payload, indexName));
    }

    @After
    public void tearDown() throws Exception {
        getConnector().dropIndex("Arenas", indexName);
        getConnector().dropCollection("Arenas");
    }
}
